version: '2'
services:
  servicioventasjh-app:
    image: servicioventasjh
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://servicioventasjh-mysql:3306/servicioventasjh?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  servicioventasjh-mysql:
    extends:
      file: mysql.yml
      service: servicioventasjh-mysql
